name: "🐛 Bug "
description: "Please write when a bug occurs."
title: "🐛 [Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Please describe the problem that occurred.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please describe the steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Please attach a screenshot to help understand.
  - type: textarea
    id: Expected-Behavior
    attributes:
      label: Expected Behavior
      description: Please describe the expected outcome when there is no bug.
  - type: textarea
    id: log
    attributes:
      label: Log
      description: Please copy and attach the error log.
      render: Shell
  - type: dropdown
    id: browser
    attributes:
      description: Please select the browser where the bug occurred.
      label: Browser
      multiple: true
      options:
        - Chrome
        - Firefox
