name: "🧪 Test"
description: "Please enter the test task."
title: "🧪 [Test] "
labels: ["test"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description for the issue.
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: Todo
      description: Please add a Todo list.
      value: "- [ ] todo1"
  - type: textarea
    id: etc
    attributes:
      label: ETC
      description: Please enter any other issue details.
